/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class info_hearit_pluginsample_PluginAudioModule */

#ifndef _Included_info_hearit_pluginsample_PluginAudioModule
#define _Included_info_hearit_pluginsample_PluginAudioModule
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     info_hearit_pluginsample_PluginAudioModule
 * Method:    configureNativeComponents
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_info_hearit_pluginsample_PluginAudioModule_configureNativeComponents
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     info_hearit_pluginsample_PluginAudioModule
 * Method:    release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_info_hearit_pluginsample_PluginAudioModule_release
  (JNIEnv *, jobject, jlong);

/*
 * Class:     info_hearit_pluginsample_PluginAudioModule
 * Method:    setGainFactor
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_info_hearit_pluginsample_PluginAudioModule_setGainFactor
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     info_hearit_pluginsample_PluginAudioModule
 * Method:    getGainFactor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_info_hearit_pluginsample_PluginAudioModule_getGainFactor
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
